name: fakemedicine
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  firebase_core: ^2.31.0
  firebase_auth: ^4.2.0
  cloud_firestore: ^4.17.5
  http: ^1.2.2
  googleapis: ^13.1.0
  googleapis_auth: ^1.6.0
  barcode_scan2: ^4.3.3
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - fonts/Urbanist-SemiBold.ttf

  fonts:
    - family: Urbanist
      fonts:
        - asset: fonts/Urbanist-SemiBold.ttf
          weight: 600
